### ISSUE TITLE
Needed refactorization in setup_parameterization

### ISSUE THREAD

**Issue by copyme** [avaxman/Directional#12]
I think this function is simply too long from the maintenance point of view, and has multiple responsibilities which should never happen. I would say that the code subdivision rule should guide us here.

**Comment by avaxman** [comment]
Definitely. Thanks for reviewing it. It was just code grown from research and I made it a nice UI, but the underlying code needs some refactoring.

**Comment by avaxman** [comment]
It's currently rebranded as setup_integration, so going to close it and leave it for future development.
