### ISSUE TITLE
Potential bug in tutorial 103

### ISSUE THREAD

**Issue by copyme** [avaxman/Directional#13]
As I understand once we tape the space button we should see a nice animation of the streamlines over the mesh. Unfortunately, the current version stops the animation after some time and it only keep allocating more memory. 

![image](https://user-images.githubusercontent.com/456607/49368249-dde59b00-f6f6-11e8-9e3d-ee2fff3d70c4.png)

The figure above shows the last frame of the animation that I can see here, and as you can see the memory allocation keeps going.

**Comment by avaxman** [comment]
Is this in Linus...? I cannot reproduce, to me it looks good on OSX, and worked the same on Windows. Perhaps there is some z-fighting and it appears underneath the surface?

**Comment by copyme** [comment]
@avaxman I have noticed that I used libigl from the dev branch. Today, i have recompiled the code with the code from the master branch and everything works well.

![image](https://user-images.githubusercontent.com/456607/49433041-b99ec280-f7b9-11e8-9e7c-20042137190e.png)

I will try to see what is causing the problem on the dev version of libigl. Let's keep this issue open for now, please.

**Comment by copyme** [comment]
@avaxman can you try this tutorial code on OS X or Windows but compiled with the current dev branch of libigl, please?

**Comment by bbrrck** [comment]
I can confirm: if compiled using the dev branch of libigl, there is indeed a problem on MacOS, too. I'm getting exactly the same result as in the first screenshot of @copyme.

**Comment by avaxman** [comment]
Should be better now.
