### ISSUE TITLE
Drop dijkstra.cpp/h and use the version from libigl

### ISSUE THREAD

**Issue by copyme** [avaxman/Directional#14]
There is no need for this modified version of libigl code anymore.

The current version of libigl has 

```
template <typename IndexType, typename DerivedD, typename DerivedP>
IGL_INLINE int igl::dijkstra(
  const IndexType &source,
  const std::set<IndexType> &targets,
  const std::vector<std::vector<IndexType> >& VV,
  Eigen::PlainObjectBase<DerivedD> &min_distance,
  Eigen::PlainObjectBase<DerivedP> &previous)
```

which assume that all the weights are equal 1 as required by Directional.

**Comment by copyme** [comment]
My point is that since Directional seems to be an extension of libigl it is probably a good idea to reduce dubled code.

**Comment by avaxman** [comment]
Yes, there is no reason for it. It was just a scaffold at the time.
