### ISSUE TITLE
streamline tracing only makes short curves due to segment_segment_intersection strange behavior

### ISSUE THREAD

**Issue by pzpzpzp1** [avaxman/Directional#19]
I'm not certain that this is a Directional error or a libIGL error but commit hash 
33510d9f1b38a5ada418729cd3ea482115024487
of the libigl repo introduces odd behavior with segment_segment_intersection.

Specifically, if I revert the changes of that commit hash, Directional traces streamlines for me perfectly. If I use latest libIGL segment_segment_intersection however, all my streamlines fail to be traced past 2 iterations. The streamline tracing each step only advances by a length of ~1e-17 if it advances at all. 

Going through libIGL comments though it seems like they made the change to fix a different bug. Perhaps they introduced a new one? Or perhaps the functionality of the method actually changed, which would need Directional to update it's usage.

**Comment by avaxman** [comment]
I opened a relevant issue in libigl since i can reproduce the problem.

**Comment by avaxman** [comment]
Should be working decently now.
