### ISSUE TITLE
dual_cycles.h: vertex2cycle numbering mixed between innerVertices and boundaryLoops

### ISSUE THREAD

**Issue by merlinyx** [avaxman/Directional#28]
Hello! I was trying to prescribe indices for boundary loops and realized that dual_cycles() was reusing some cycle numbers of internal vertices for boundary loops:
https://github.com/avaxman/Directional/blob/master/include/directional/dual_cycles.h#L175-L192

It seems that L191 should be changed from
        vertex2cycle(boundaryLoops[i][j])=i;
to 
        vertex2cycle(boundaryLoops[i][j])= innerVerticesList.size() + i;

This way, changing indices on boundary loops would not affect the indices for some inner vertices.

**Comment by avaxman** [comment]
yes, it seems correct, see also line above ("numV+i").

**Comment by avaxman** [comment]
The bug was fixed. As a nice side effect, the entire boundary index is shown by colors on all its vertices.
