### ISSUE TITLE
MIQ - How do I lift the grid?

### ISSUE THREAD

**Issue by kabukunz** [avaxman/Directional#30]
Thank you for this library, it looks very useful and interesting. 
I'm experimenting with some remeshing. I've set up the tuts to generate a powerfield, a curl reduction, and then a miq, with the goal of extracting a good, possibly pure, quad mesh from a triangle mesh with lots of imperfections and slivers. In short from this

<img width="366" alt="powerf" src="https://user-images.githubusercontent.com/33091053/74750773-8c2e1f80-526c-11ea-87c7-315adfc333b5.png">

to this:

<img width="354" alt="Screenshot 2020-02-18 at 15 31 06" src="https://user-images.githubusercontent.com/33091053/74750820-a405a380-526c-11ea-9525-f3cb82472bf7.png">

But I miss the last step. I have the final parameterization, but I don't know how to "lift the grid", how to recreate the original mesh with the new quad tessellation.

The parameterization interface returns cutUVFull. So I guess I should reconstruct the tessellation back point by point... I don't know if something else in ParameterizationData can help...

I've checked this Qex library, but it's completely on its own... let alone the awkward licensing... and I need to understand the process anyway...

**Comment by copyme** [comment]
@kabukunz If we talk about mesh extraction then the code is not ready yet. There exists an early version but it is not ready for public use, even if we use it for an ongoing project.

**Comment by kabukunz** [comment]
Yes, that one. I still don't grasp the subject clearly. Probably I should focus on understanding how to revert a parameterization first... 
Thanks for the answer.

**Comment by avaxman** [comment]
Hi @kabukunz,

Sorry for the late reply - currently in a parental leave! 

Anyhow, Kacper is right: one should currently use QEx to do the actual lift (the quad mesh from the parameterization). We are currently at work to replace it with an in-house mesher that will be in a future release of Directional.

Amir.

**Comment by kabukunz** [comment]
I'm using Qex for now. I still don't grasp how it can reverse a parameterization without knowing the mapping function, but clearly it's possible - I have to think about it someway better and experiment some more...
Thank you for the reply. All the best!

**Comment by copyme** [comment]
@kabukunz Once you have (u,v)s per triangle you do not need anything else. Think about a single triangle. It is in 3D but the uvs tell you where the triangle vertices are mapped in the UV-plane. So, draw the triangle there using uvs per vertex. Then you just need a standard square grid. The closer the vertices' uvs are to each other the more grid lines will pass your triangle, and vice versa. 

You can take a grid paper sheet and just play with different uvs for a single triangle, etc.

**Comment by copyme** [comment]
@kabukunz I can give you some simple examples that you can draw in GeoGebra, for example, and see that uvs, are enough.

**Comment by kabukunz** [comment]
So apparently I had it more complicated than it was. 


> The closer the vertices' uvs are to each other the more grid lines will pass your triangle, and vice versa.

Just for exemplification, if I subdivide the uv I'll get more lines. It only matters not changing the position of the "original" vertices, so as not to break the isoline created by miq.
And while redrawing 2d and then "folding" it back to 3d... lines will "snap" because parallel transport has already been accounted for in the paramt. by creating separatrices, by cutting...

Ok. I think I've got it. Now it just matters to find a way to have everything faster... even in release eigen computation is soo slow... actually it's a pain to go beyond a meager 10K tris... this makes real world applications very difficult.

Thank you for your help. Very appreciated.

**Comment by copyme** [comment]
I mean further away, and I was referring to another step. But you got the idea. Yes, you need some vertices to sit on integers, etc.
