### ISSUE TITLE
503_HexagonalParameterization -- directional::setup_parameterization called with wrong input

### ISSUE THREAD

**Issue by olkido** [avaxman/Directional#31]
The hexagonal parameterization tutorial won't build -- it calls diagonal::setup_parameterization with an integer input N but instead a symmFunc matrix is needed according to the function prototype. Here's the error log:

/Users/olkido/Dropbox/Work/code/Directional/tutorial/503_HexagonalParameterization/main.cpp:140:39: error: 
      reference to type 'const Eigen::MatrixXi' (aka 'const
      Matrix<int, Dynamic, Dynamic>') could not bind to an lvalue of
      type 'int'
  directional::setup_parameterization(N, VMeshWhole, FMeshWhol...
                                      ^
/Users/olkido/Dropbox/Work/code/Directional/cmake/../include/directional/setup_parameterization.h:63:65: note: 
      passing argument to parameter 'symmFunc' here
  ...void setup_parameterization(const Eigen::MatrixXi& symmFunc,
                                                        ^
1 error generated.
make[2]: *** [503_HexagonalParameterization/CMakeFiles/503_HexagonalParameterization_bin.dir/main.cpp.o] Error 1
make[1]: *** [503_HexagonalParameterization/CMakeFiles/503_HexagonalParameterization_bin.dir/all] Error 2
make: *** [all] Error 2

**Comment by avaxman** [comment]
This is currently unsupported (will be part of a bigger change to parameterization that's going to happen soon). I put it out of the project.
