### ISSUE TITLE
501_SeamlessParameterization   -- wrong number of arguments in call. 

### ISSUE THREAD

**Issue by olkido** [avaxman/Directional#32]
This tutorial won't build out of the box, the call to directional::parameterize has 10 arguments while the function prototype requires 12. I believe I fixed this by adding two dummy arguments and using as follows 

  Eigen::MatrixXd dummy1, dummy2;
  std::cout<<"Solving parameterization"<<std::endl;
  directional::parameterize(VMeshWhole, FMeshWhole, FE, combedField, lengthRatio, pd, VMeshCut, FMeshCut, isInteger, dummy1, cutUV, dummy2);
  cutUV=cutUV.block(0,0,cutUV.rows(),2);
  std::cout<<"Done!"<<std::endl;

(Note that my first choice of appending the dummy arguments at the end of the argument list gave me errors having to do with wrong matrix sizes). Please check if that's correct.  I believe the same is true for 502_MixedIntegerParameterization.

**Comment by avaxman** [comment]
Fixed now. A bit off the tutorial but this will get wrapped soon. Anyhow working :-)
