### ISSUE TITLE
Some tutorials do not compile on MSVC

### ISSUE THREAD

**Issue by copyme** [avaxman/Directional#39]
For instance, in the file ```point_spheres.h``` Directional depends on ```M_PI```, which is not a part of the standard. In order, to enable these the preprocessor has to define ```_USE_MATH_DEFINES```. 

This can be solved by for instance adding 
```
if(MSVC)
  add_compile_definitions(_USE_MATH_DEFINES)
endif()
```
to the ```CMakeLists.txt``` file. Also, I think there is a possibility of using ```igl::pi``` instead.

**Comment by avaxman** [comment]
I was able to compile the entire library tutorials in MSVC, and replaced all these instances with the igl::PI.
