### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by copyme** [avaxman/Directional#40]
In ```dual_cycles.h``` the code uses ```std::set``` but the ```include <set>``` is missing. 

Also, in tutorial 301 we have ```#include <igl/read_triangle_mesh.h>``` but in the code is used ```igl::readOBJ``` which is not included. Similarly, in 302 we have ```readOFF``` but only ```#include <igl/read_triangle_mesh.h>``` is present.

**Comment by avaxman** [comment]
Fixed.
