### ISSUE TITLE
Parameterize using the vertex indices of the original mesh

### ISSUE THREAD

**Issue by fire** [avaxman/Directional#41]
Parameterize a mesh using the vertex indices of the original mesh. Would that be possible? Want to request a tutorial on it.

I forgot to add. The opposite of subdivision levels is used on this.

**Comment by avaxman** [comment]
I am not entirely sure what you are looking for. What kind of parameterization? In general, a field cannot be integrated into a vertex-based function unless it's a gradient field, but this is not what people call a parameterization: one needs to cut the mesh, and then some corners of vertices must be split.

What is the application with subdivision that you are referring to?

**Comment by fire** [comment]
I thought about the use case more.

I think the only requirement is a way to generate a manifold mesh.

https://github.com/zeux/meshoptimizer/issues/222

If this library or any pipeline stages can generate a manifold mesh, I can use it.

**Comment by fire** [comment]
I'll close this because I had some good experiences with https://github.com/gradientspace/geometry3cpp. I'll make a new issue about requirements for directional meshes.
