### ISSUE TITLE
Question regarding using directional::power_field with constrains

### ISSUE THREAD

**Issue by ioannaMitropoulou** [avaxman/Directional#42]
Hello and many thanks for this awesome library!

I have a question regarding calculating fields with predefined alignment constraints. I am using the `directional::power_field` in order to find the smooth field that interpolates the constraints that are saved in the `b` and `bc `lists. However, I notice a difference in the results depending on the N parameter. 

When I use N=1, the resulting field respects the direction of the constraints. However, when N=2 with the same constraints, the field seems to be rotated 90 degrees. What I expected to see was that the representative of each face would be aligned with the constraints, but maybe I have misunderstood how the function works. Instead, as I increase N, I get vector fields rotated with respect to the constraints. Below I attach some screenshots on an example-mesh (the constraints are the same, only N changes). 

For N=1 the resulting field is aligned with the constraints.
![image](https://user-images.githubusercontent.com/17250275/104440171-508df980-5592-11eb-9702-ad2ddfacf779.png)

For N>1 all components are rotated.
![image](https://user-images.githubusercontent.com/17250275/104440211-5b488e80-5592-11eb-91a5-a05552018f66.png)

![image](https://user-images.githubusercontent.com/17250275/104440282-70bdb880-5592-11eb-9e6d-4f3c52683188.png)

I suppose getting the direction I want is just a matter of applying the correct rotation to the resulting field. Could you explain the logic behind this rotation?

On a second note, I noticed that the function `directional::write_matching` returns False when it succeeds, a negation seems to be missing there.

Many thanks for your time!
Ioanna

**Comment by avaxman** [comment]
Thanks for the depiction. Can you send the files so I could reproduce? I think this is related to a bug I just fixed in which power fields and polyvectors differe by a minus (and so the constraints would indeed rotate like a bisector or 90 degrees). Can you in addition update your Directional version and try again?

**Comment by ioannaMitropoulou** [comment]
Hello,
Thanks for your quick reply, indeed it seems to be working now! 
I attach some screenshots with the results. I will let you know if I notice any other unexpected behavior.

![image](https://user-images.githubusercontent.com/17250275/104448147-12e29e00-559d-11eb-9fd7-62858dca89fa.png)

![image](https://user-images.githubusercontent.com/17250275/104448105-09593600-559d-11eb-984a-d55f66c08af8.png)

![image](https://user-images.githubusercontent.com/17250275/104448205-255cd780-559d-11eb-9b87-cd353def220d.png)

Thanks!
Ioanna

**Comment by avaxman** [comment]
Looks great! glad you could find the library useful.
