### ISSUE TITLE
Requirements for input meshes?

### ISSUE THREAD

**Issue by fire** [avaxman/Directional#46]
What are the requirements for input meshes?

Speculatively it has to be manifold or can this be relaxed?

**Comment by avaxman** [comment]
The mesh needs to be strictly 2-manifold, and consistently oriented. It can have any genus or boundary loops. In the current version you must also have a single connected component (so no two meshes in a single file), but I might relax it.

**Comment by fire** [comment]
Relaxing the connected restriction would be good, if not I’d have run the operation split.

**Comment by avaxman** [comment]
That's right. The algorithms themselves are anyhow only defined for connected components so this is a software issue.

**Comment by fire** [comment]
Can you leave a note in the documentation?

**Comment by avaxman** [comment]
Yes, I leave the issue open and will do so, notifying by closing it.

**Comment by avaxman** [comment]
The note on the requirement from the input was added to the "discretization" subsection in the tutorial.
