### ISSUE TITLE
Quad remeshing (Handling with non-manifold meshes)

### ISSUE THREAD

**Issue by fire** [avaxman/Directional#48]
Can you suggest solution or readings for dealing with non manifold meshes that I can then make manifold and submit to directional?

The goal is quad re-meshing game characters that were originally triangulated with the constraint that the bending would be aesthetically pleasing and the result can be subdivided.

Edited:

The goal is to handle:

1. vertices
1. indices
1. normals (per vertex and per tangent)
1. uvs
1. bones
1. weights

**Comment by avaxman** [comment]
If I understand correctly, you want an animation-friendly quadrangulation? that is a problem not solved by research, AFAIK. I have students working on relevant things. In the meantime, you can check https://cims.nyu.edu/gcl/papers/animation-aware-quadrangulation-2013.pdf and follow-up papers.
