### ISSUE TITLE
Possible typo in the tutorial description

### ISSUE THREAD

**Issue by copyme** [avaxman/Directional#7]
There is 

> However, note that every conversion is possible; for instance, it is not possible to convert between PolyVectors and rotation angles, as they do not possess the same power of expression (with current state-of-the-art…).

But I think it should be

> However, note that **not** every conversion is possible; for instance, it is not possible to convert between PolyVectors and rotation angles, as they do not possess the same power of expression (with current state-of-the-art…).

There is 

> a cycle around the vertex. a directional must return to itself after a cycle,

most likely there should be

> a cycle around the vertex. **A** directional must return to itself after a cycle,

This phrase reads strange:

> We see a field that _in smooth in the Cartesian sense_, with more uniformly-placed singularities.

In the section: 304 Conjugate Fields, there is

> **,** where k_1 and k_2

but just a line above there is a full stop at the end of the equations. This full stop should be replaced with the comma.

Lost reference

>  by simple iterative rounding [^Bommes_2009]:

**Comment by copyme** [comment]
Another one. There is 

> a cycle around the vertex. a directional must return to itself after a cycle,

most likely there should be

> a cycle around the vertex. **A** directional must return to itself after a cycle,

**Comment by avaxman** [comment]
Hi Kacper,

Can you put them all under the same issue? Thanks!

Amir.

**Comment by copyme** [comment]
Hi Amir, sure I will do so.
